id: P002960
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01633
  title: དུས་ཀྱི་འཁོར་ལོའི་རིམ་གཉིས་འབྲོ་ལུགས་ཀྱི་བརྒྱུད་པའི་གསོལ་འདེབས
  author: ''
  volumes:
    d500c093fbf3457d99bb24f12455cfc9:
      image_group_id: I00KG02925
      title: ''
      volume_number: 1
      total_pages: 10
      base_file: v001.txt
