id: I08691294
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:37:29+00:00'
last_modified: '2022-06-07T16:35:00.956741+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01633
  title: དུས་ཀྱི་འཁོར་ལོའི་རིམ་གཉིས་འབྲོ་ལུགས་ཀྱི་བརྒྱུད་པའི་གསོལ་འདེབས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0CC7:
      image_group_id: I00KG02925
      title: ''
      total_pages: 10
      order: 1
      base_file: 0CC7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
